# Generated by Django 5.0.6 on 2024-06-28 07:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='deliveryboy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('phno', models.IntegerField()),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('proof', models.FileField(upload_to='')),
                ('status', models.CharField(default='pending', max_length=10, null=True)),
                ('work_status', models.CharField(default='free', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Mail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=15)),
                ('state', models.CharField(max_length=15)),
                ('country', models.CharField(max_length=15)),
                ('zip_code', models.CharField(max_length=10, null=True)),
                ('phone', models.CharField(max_length=15)),
                ('quantity', models.IntegerField(default=1)),
                ('total_price', models.IntegerField()),
                ('payment_status', models.CharField(max_length=20, null=True)),
                ('purchase_date', models.DateTimeField(auto_now=True, null=True)),
                ('product_status', models.CharField(default='Order Placed', max_length=50, null=True)),
                ('instruction', models.CharField(default='Your Order Has Been Successfully Placed', max_length=50, null=True)),
                ('delivery_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_name', models.CharField(max_length=300)),
                ('Price', models.IntegerField()),
                ('Stock', models.IntegerField()),
                ('image', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('phno', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=505)),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='orderitem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_detaill', models.CharField(max_length=20)),
                ('delivery', models.CharField(max_length=20)),
                ('quantity', models.IntegerField()),
                ('price', models.IntegerField()),
                ('status', models.CharField(default='pending', max_length=20)),
                ('order_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pantry.order')),
                ('product_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pantry.product')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='product_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pantry.product'),
        ),
        migrations.CreateModel(
            name='PasswordReset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pantry.register')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pantry.register'),
        ),
        migrations.CreateModel(
            name='cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, null=True)),
                ('product_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pantry.product')),
                ('user_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pantry.register')),
            ],
        ),
        migrations.CreateModel(
            name='wish_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, null=True)),
                ('product_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pantry.product')),
                ('user_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pantry.register')),
            ],
        ),
    ]
