# Generated by Django 5.2 on 2025-04-23 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pantry', '0002_alter_order_delivery_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='phno',
            new_name='phone',
        ),
    ]
