# Generated by Django 6.0.5 on 2026-05-19 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pantry', '0003_rename_phno_register_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryboy',
            name='phno',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='register',
            name='phone',
            field=models.BigIntegerField(),
        ),
    ]
